version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bioDB

  adminer:
    image: adminer
    container_name: mysql_adminer
    restart: always
    ports:
      - 8081:8080
